Repository TikkleSaver/FE, pull requests merged in 2025-06, with the labels that each got.

#108 [FEAT] 지출 분석 페이지 API 연결
  src/api/expense/expenseAnalysisApi.js
  src/components/header/ExpenseMenu.jsx
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseAnalysis.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: ✨ Feature, 🔨 Refactor

#110 [REFACTOR] 지출 관련 디테일 수정
  src/api/expense/expenseCalendarApi.js
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseAnalysis.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: 🔨 Refactor

#115 [Feat] 나의 위시리스트 구매완료 api 연결
  src/api/wish/wish.js
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/wish/MyWishPage.jsx
Labels: ✨ Feature

#116 [Feat] 상품 위시에 추가 api 연결
  src/api/wish/wish.js
  src/pages/product/ProductPage.jsx
  src/pages/wish/AddWishExistPage.jsx
  src/pages/wish/AddWishNotExistPage.jsx
Labels: ✨ Feature

#120 [Feat] 친구 위시 조회 api 연동
  src/api/wish/wishAPI.js
  src/components/friend/FriendCard.jsx
  src/components/wish/FriendwishPlannedComponent.jsx
  src/components/wish/FriendwishPurchasedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/wish/FriendWishPage.jsx
Labels: ✨ Feature

#124 [Feat] 내 위시 수정/삭제 api 연동
  src/api/wish/wishAPI.js
  src/components/wish/MywishPlannedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/wish/AddWishNotExistPage.jsx
  src/pages/wish/UpdateWishExistPage.jsx
  src/pages/wish/UpdateWishNotExistPage.jsx
  src/pages/wish/WishInfoPage.jsx
Labels: ✨ Feature

#128 [Feat] 위시 공개/위시 구매/위시 만족 api 연동
  src/api/wish/wishAPI.js
  src/components/wish/MywishPlannedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/wish/AddWishExistPage.jsx
Labels: ✨ Feature

#137 [Refac] 위시 디테일 수정
  src/components/header/MainHeader.jsx
  src/components/header/WishListMenu.jsx
  src/components/meddling/MeddlingPreviewCard.jsx
  src/components/wish/FriendwishPlannedComponent.jsx
  src/components/wish/FriendwishPurchasedComponent.jsx
  src/components/wish/MywishPlannedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/product/ProductDetailPage.jsx
  src/pages/product/ProductPage.jsx
  src/pages/wish/AddWishExistPage.jsx
  src/pages/wish/AddWishNotExistPage.jsx
  src/pages/wish/UpdateWishExistPage.jsx
  src/pages/wish/UpdateWishNotExistPage.jsx
  src/pages/wish/WishInfoPage.jsx
Labels: 🔨 Refactor

#139 [FEAT] 챌린지 검색 api 연결
  package-lock.json
  package.json
  src/App.js
  src/api/challenge/searchChallengeApi.js
  src/assets/categoryIcon.svg
  src/components/challenge/ChallengePreviewCard.jsx
  src/components/challenge/Dropdown.jsx
  src/pages/challenge/ChallengeListPage.jsx
  src/pages/challenge/ChallengePage.jsx
  src/pages/challenge/ChallengeSearchPage.jsx
  src/pages/challenge/SignUpChallengePage.jsx
Labels: ✨ Feature

#144 [Refac] 직접 추가 버튼 위치 수정
  src/pages/product/ProductPage.jsx
Labels: 🔨 Refactor

#147 [FEAT] 챌린지 디테일 멤버 별 페이지 화면 처리
  src/App.js
  src/api/challenge/challengeDetailApi.js
  src/api/challenge/challengeListApi.js
  src/assets/edit.svg
  src/assets/plus.svg
  src/components/challenge/ ChallengeExitModal.jsx
  src/components/challenge/ChallengRequestCard.jsx
  src/components/challenge/ChallengeCertifyComponent.jsx
  src/components/challenge/ChallengeMainComponent.jsx
  src/components/challenge/ChallengeRequestModal.jsx
  src/components/challenge/ChallengerComponent.jsx
  src/pages/challenge/ChallengeDetailPage.jsx
  src/pages/challenge/ChallengeListPage.jsx
  src/pages/challenge/CreateChallengePage.jsx
  src/pages/challenge/SignUpChallengePage.jsx
Labels: ✨ Feature

#157 [FEAT] 푸터 적용
  src/App.js
  src/assets/githubIcon.svg
  src/components/challenge/ChallengerComponent.jsx
  src/components/footer/MainFooter.jsx
  src/pages/challenge/ChallengeDetailPage.jsx
Labels: ✨ Feature, 🔨 Refactor

#165 [FEAT] 지출 관련 헤더 설정
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseAnalysis.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: ✨ Feature

#168 [html&css] 카테고리 색 설정
  src/constanst/color.mjs
Labels: 🎨 Html&css

#172 [FIX] 참여중인 챌린지 경로 수정
  src/components/challenge/ChallengePreviewCard.jsx
  src/components/header/ChallengeMenu.jsx
  src/pages/challenge/ChallengeSearchPage.jsx
  src/pages/myprofile/JoinedChallengeListPage.jsx
  src/pages/myprofile/MyProfile.jsx
Labels: 🐞 BugFix, 🔨 Refactor

#173 [FIX] 챌린지 수정하기 수정
  src/pages/challenge/UpdateChallengePage.jsx
Labels: 🔨 Refactor
