Repository TikkleSaver/FE, pull requests merged in 2025-05, with the labels that each got.

#15 [FEAT] 참견소 페이지 UI 구현
  src/App.js
  src/components/header/MainHeader.jsx
  src/components/meddle/MeddlingPreviewCard.jsx
  src/images/Meddling/Agree.png
  src/images/Meddling/DisAgree.png
  src/images/Meddling/comment.png
  src/images/Meddling/satisfaction.png
  src/pages/meddling/MeddlingPage.jsx
Labels: ✨ Feature

#19 [Refactor] ExpenseCalendar 파일 위치 변경
  src/pages/expense/ExpenseCalendar.jsx
Labels: 🔨 Refactor

#21 [Refactor] ExpenseCalendar 파일 위치 변경
  src/App.js
Labels: 🔨 Refactor

#16 [FEAT] 상품 검색 UI 구현
  src/App.js
  src/components/header/MainHeader.jsx
  src/components/header/WishListHeader.jsx
  src/components/product/ProductPreviewCard.jsx
  src/pages/product/ProductPage.jsx
Labels: ✨ Feature

#22 [Feat] 지출 목록 조회 페이지 UI 구현
  src/App.js
  src/assets/arrowUp.svg
  src/assets/defaultProfile.svg
  src/assets/etc-vertical.svg
  src/assets/food.jpg
  src/assets/pen.svg
  src/assets/trash.svg
  src/components/expense/FriendCommentCard.jsx
  src/components/expense/FriendExpenseCard.jsx
  src/components/expense/MyCommentCard.jsx
  src/components/expense/MyExpenseCard.jsx
  src/components/header/MainHeader.jsx
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: ✨ Feature

#26 [Feat] 지출 등록하기 모달 UI 구현
  src/assets/camera.svg
  src/components/expense/modal/AddExpenseModal.jsx
  src/pages/expense/Expense.jsx
Labels: ✨ Feature, 🎨 Html&css

#27 [Html&Css] 폰트, 색상 지정
  src/App.js
  src/assets/fonts/woff2/PretendardVariable.woff2
  src/components/challenge/ChallengeCertifyComponent.jsx
  src/components/challenge/ChallengeMainComponent.jsx
  src/components/challenge/ChallengerComponent.jsx
  src/constanst/color.mjs
  src/styles/GlobalStyle.jsx
Labels: 🎨 Html&css

#37 [FEAT] 상품 상세 보기 ui 구현
  src/App.js
  src/assets/productAdd.svg
  src/pages/product/ProductDetailPage.jsx
Labels: ✨ Feature

#39 [FEAT] 기존 존재 상품 추가 ui 구현
  src/App.js
  src/assets/wishLock.svg
  src/pages/product/ProductDetailPage.jsx
  src/pages/wish/AddWishExistPage.jsx
Labels: ✨ Feature

#43 [Html&Css] 가계부 구현된 UI에 색상 지정
  src/components/expense/FriendCommentCard.jsx
  src/components/expense/FriendExpenseCard.jsx
  src/components/expense/MyCommentCard.jsx
  src/components/expense/MyExpenseCard.jsx
  src/components/expense/modal/AddExpenseModal.jsx
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: 🎨 Html&css

#45 [FEAT] 지출 수정하기 모달 UI 구현
  src/components/expense/MyExpenseCard.jsx
  src/components/expense/modal/UpdateExpenseModal.jsx
Labels: ✨ Feature

#46 Feat/mypage/#35
  src/App.js
  src/components/challenge/ChallengePreviewCard.jsx
  src/components/header/MainHeader.jsx
  src/components/header/ProfileMenu.jsx
  src/components/header/WishListHeader.jsx
  src/images/header/logout_icon.svg
  src/images/header/profile_icon1.svg
  src/images/header/profile_icon2.svg
  src/images/myprofile/cover.svg
  src/images/myprofile/edit_icon.svg
  src/images/myprofile/edit_icon2.svg
  src/images/myprofile/friend.svg
  src/images/myprofile/friend_gray.svg
  src/images/myprofile/pw_icon.svg
  src/images/profile.svg
  src/pages/myprofile/EditProfile.jsx
  src/pages/myprofile/MyProfile.jsx
  src/pages/myprofile/SavedChallenge.jsx
Labels: ✨ Feature, 🎨 Html&css

#50 [FEAT] 지출 분석 페이지 UI 구현
  package-lock.json
  package.json
  src/App.js
  src/components/header/ExpenseMenu.jsx
  src/components/header/MainHeader.jsx
  src/pages/expense/ExpenseAnalysis.jsx
Labels: ✨ Feature

#41 [FEAT] 기존 존재 상품 위시 수정 ui 구현
  src/App.js
  src/pages/wish/UpdateWishExistPage.jsx
Labels: ✨ Feature

#53 [FEAT] 기존 존재하지 않던 상품 위시 수정 ui 구현
  src/App.js
  src/pages/wish/UpdateWishNotExistPage.jsx
Labels: ✨ Feature

#59 [Feat] 위시 상세 보기 ui 구현
  src/App.js
  src/components/meddle/MeddlingPreviewCard.jsx
  src/components/wish/WishCommentCard.jsx
  src/images/Meddling/Agree.png
  src/images/Meddling/DisAgree.png
  src/images/Meddling/comment.png
  src/images/Meddling/satisfaction.png
  src/pages/wish/WishInfoPage.jsx
Labels: ✨ Feature

#61 [Html&Css] 위시 관련 ui 디테일 수정
  src/App.js
  src/assets/wishEmptyImg.svg
  src/assets/wishLock.svg
  src/assets/wishLockGrey.svg
  src/assets/wishUnlock.svg
  src/components/header/WishListHeader.jsx
  src/components/meddle/MeddlingPreviewCard.jsx
  src/components/product/ProductPreviewCard.jsx
  src/components/wish/FriendwishPlannedComponent.jsx
  src/components/wish/FriendwishPurchasedComponent.jsx
  src/components/wish/MywishPlannedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/constanst/color.mjs
  src/images/wishProduct.png
  src/images/wishProductImg.png
  src/pages/meddling/MeddlingPage.jsx
  src/pages/product/ProductDetailPage.jsx
  src/pages/product/ProductPage.jsx
  src/pages/wish/AddWishExistPage.jsx
  src/pages/wish/AddWishNotExistPage.jsx
  src/pages/wish/FriendWishPage.jsx
  src/pages/wish/MyWishPage.jsx
  src/pages/wish/UpdateWishExistPage.jsx
  src/pages/wish/UpdateWishNotExistPage.jsx
  src/pages/wish/WishInfoPage.jsx
Labels: 🎨 Html&css

#64 [Feat] 챌린지 검색 결과 ui 구현
  src/App.js
  src/pages/challenge/ChallengeSearchPage.jsx
Labels: ✨ Feature

#70 [HtmlCss] 위시 상품 정보 폰트 조절, 나의 위시리스트 드롭다운 수정
  src/components/header/MainHeader.jsx
  src/components/header/WishListHeader.jsx
  src/components/header/WishListMenu.jsx
  src/components/meddling/MeddlingPreviewCard.jsx
  src/components/wish/FriendwishPlannedComponent.jsx
  src/components/wish/FriendwishPurchasedComponent.jsx
  src/components/wish/MywishPlannedComponent.jsx
  src/components/wish/MywishPurchasedComponent.jsx
  src/pages/meddling/MeddlingPage.jsx
Labels: 🎨 Html&css

#71 [Feat] 네이버 쇼핑 API 연동
  .gitignore
  package-lock.json
  package.json
  src/api/naver.js
  src/components/product/ProductPreviewCard.jsx
  src/pages/product/ProductPage.jsx
Labels: ✨ Feature

#76 [Feat] 네이버 상품 요소 수정, 관련 경로 연결
  src/api/naver.js
  src/components/product/ProductPreviewCard.jsx
  src/pages/product/ProductDetailPage.jsx
  src/pages/product/ProductPage.jsx
  src/pages/wish/AddWishExistPage.jsx
Labels: ✨ Feature, 🎨 Html&css

#73 [FEAT] 챌린지 카테고리별 조회 api 연결
  package.json
  src/App.js
  src/components/challenge/ChallengePreviewCard.jsx
  src/components/header/ChallengeMenu.jsx
  src/components/pagination/Pagination.jsx
  src/pages/challenge/ChallengeListPage.jsx
Labels: ✨ Feature

#79 [FEAT] 챌린지 가입하기 페이지 조회 api 연결
  src/App.js
  src/assets/privateChallenge.svg
  src/assets/scraped.svg
  src/components/challenge/ChallengePreviewCard.jsx
  src/pages/challenge/ChallengeListPage.jsx
  src/pages/challenge/CreateChallengePage.jsx
  src/pages/challenge/SignUpChallengePage.jsx
Labels: ✨ Feature

#81 [Feat] 존재 상품 위시 추가 API 연결
  src/api/wish.js
  src/assets/wishUnlockGrey.svg
  src/pages/product/ProductPage.jsx
  src/pages/wish/AddWishExistPage.jsx
Labels: ✨ Feature

#86 [FEAT] 챌린지 스크랩, 가입 요청 api 연결
  src/api/naver.js
  src/components/challenge/ChallengePreviewCard.jsx
  src/pages/challenge/CreateChallengePage.jsx
  src/pages/challenge/SignUpChallengePage.jsx
Labels: ✨ Feature

#89 [FEAT] 지출 등록/수정/삭제/조회 api 연결
  src/api/expense/expenseApi.js
  src/components/expense/MyExpenseCard.jsx
  src/components/expense/modal/AddExpenseModal.jsx
  src/components/expense/modal/UpdateExpenseModal.jsx
  src/pages/expense/Expense.jsx
  src/pages/expense/ExpenseCalendar.jsx
Labels: ✨ Feature

#91 [FIX] 친구 지출 페이지 접속 오류 문제 해결
  src/components/expense/FriendExpenseCard.jsx
Labels: 🐞 BugFix

#96 [FEAT] 지출 달력 페이지 API 연결(JWT포함)
  src/api/axiosInstance.js
  src/api/expense/expenseCalendarApi.js
  src/pages/expense/ExpenseCalendar.jsx
Labels: ✨ Feature
